apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-gte
  namespace: default
  labels:
    app: vllm-gte
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-gte
  template:
    metadata:
      labels:
        app: vllm-gte
    spec:
      volumes:
      - name: cache-volume
        persistentVolumeClaim:
          claimName: vllm-gte-models
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: "8Gi"
      containers:
      - name: vllm-server
        image: vllm/vllm-openai:latest
        command: ["/bin/sh", "-c"]
        args: [
          "vllm serve thenlper/gte-small --trust-remote-code"
        ]
        env:
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token-secret
              key: token
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "8"
            memory: "16Gi"
            nvidia.com/gpu: "1"
          requests:
            cpu: "4"
            memory: "12Gi"
            nvidia.com/gpu: "1"
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: cache-volume
        - name: shm
          mountPath: /dev/shm
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 300000
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5 
