apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-gte
  namespace: default
  labels:
    app: vllm-gte
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: vllm-gte
  template:
    metadata:
      labels:
        app: vllm-gte
    spec:
      volumes:
      - name: cache-volume
        persistentVolumeClaim:
          claimName: vllm-gte-models
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: "8Gi"
      containers:
      - name: vllm-server
        image: vllm/vllm-openai:latest
        command: ["/bin/sh", "-c"]
        args: [
          "vllm serve Alibaba-NLP/gte-Qwen2-7B-instruct --gpu-memory-utilization 0.25 --trust-remote-code"
        ]
        env:
        - name: VLLM_LOGGING_LEVEL
          value: DEBUG
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token-secret
              key: token
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "4"
            memory: "8Gi"
            nvidia.com/gpu: "1"
          requests:
            cpu: "2"
            memory: "6Gi"
            nvidia.com/gpu: "1"
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: cache-volume
        - name: shm
          mountPath: /dev/shm
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 300000
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
