apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-llama-models
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
  volumeMode: Filesystem 