apiVersion: v1
kind: Service
metadata:
  name: vision-embedding
  namespace: default
spec:
  ports:
  - name: http-vision-embedding
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: vision-embedding
  sessionAffinity: None
  type: ClusterIP 